// BCPL playground tutorial track.
//
// Each TRACK entry names a file at site/examples/<slug>.b and carries
// metadata the Examples tab shows as you preview the lesson. The
// track is ordered; Prev/Next navigation walks it in this order.
//
// Keep this file in sync with site/examples/*.b. A lesson file whose
// slug isn't in TRACK still shows in the Examples list (as a loose
// demo), but without tutorial metadata or prev/next navigation.

export const LEVELS = [
  { n: 1, name: "First Steps"       },
  { n: 2, name: "Control Flow"      },
  { n: 3, name: "Functions & Scope" },
  { n: 4, name: "Data Structures"   },
  { n: 5, name: "I/O & System"      },
  { n: 6, name: "Advanced"          },
  { n: 7, name: "Objects"           },
  { n: 8, name: "Coroutines"        },
  { n: 9, name: "Graphics"          },
];

export const TRACK = [
  // ---- Level 1 — First Steps ------------------------------------
  {
    slug: "01-hello",
    title: "Hello, BCPL",
    level: 1,
    topic: "basics",
    summary: "Your first BCPL program. SECTION, GET, writef, start/RESULTIS.",
    goals: [
      "Declare a SECTION and GET \"libhdr\"",
      "Write a start() function returning an int",
      "Call writef with the *n newline escape",
    ],
    prereqs: [],
  },
  {
    slug: "02-comments",
    title: "Comments",
    level: 1,
    topic: "basics",
    summary: "// line comments and /* ... */ block comments.",
    goals: [
      "Use line comments for brief notes",
      "Use block comments to disable larger regions",
      "Know that BCPL block comments do not nest",
    ],
    prereqs: ["01-hello"],
  },
  {
    slug: "03-variables",
    title: "Variables & Expressions",
    level: 1,
    topic: "basics",
    summary: "LET, :=, integer arithmetic, number formats.",
    goals: [
      "Declare locals with LET",
      "Reassign with :=",
      "Use +, -, *, /, MOD, integer precedence",
      "Read decimal, hex (#x), octal (#o), binary (#b) literals",
    ],
    prereqs: ["01-hello"],
  },
  {
    slug: "04-strings-chars",
    title: "Strings & Characters",
    level: 1,
    topic: "basics",
    summary: "BCPL string layout (length byte + chars) and the % byte operator.",
    goals: [
      "Know that s%0 is the string length",
      "Index into a string with s%i (1..n)",
      "Use writef %s vs %c",
      "Write escape sequences *n *s *t *\" *'",
    ],
    prereqs: ["03-variables"],
  },

  // ---- Level 2 — Control Flow ----------------------------------
  {
    slug: "05-conditionals",
    title: "IF, UNLESS, TEST",
    level: 2,
    topic: "control",
    summary: "Three forms of conditional plus the -> ternary expression.",
    goals: [
      "IF cond DO stmt",
      "UNLESS cond DO stmt (IF ~cond)",
      "TEST cond THEN … ELSE …",
      "Expression form: a -> b, c",
    ],
    prereqs: ["03-variables"],
  },
  {
    slug: "06-boolean-short-circuit",
    title: "Boolean Evaluation",
    level: 2,
    topic: "control",
    summary: "& and | short-circuit in Boolean context; act bitwise on values.",
    goals: [
      "Short-circuit & and | inside IF/WHILE/TEST",
      "Bitwise & and | in arithmetic context",
      "~ in Boolean vs bitwise context",
    ],
    prereqs: ["05-conditionals"],
  },
  {
    slug: "07-for-loop",
    title: "FOR loops",
    level: 2,
    topic: "control",
    summary: "FOR with BY, nested loops, LOOP/BREAK/NEXT/EXIT.",
    goals: [
      "FOR i = a TO b DO …",
      "Custom step with BY",
      "LOOP skips to next iteration; BREAK exits the enclosing loop",
      "NEXT/EXIT in MATCH/EVERY",
    ],
    prereqs: ["05-conditionals"],
  },
  {
    slug: "08-while-until",
    title: "WHILE, UNTIL, REPEAT",
    level: 2,
    topic: "control",
    summary: "Head-tested and tail-tested loops.",
    goals: [
      "WHILE cond DO body",
      "UNTIL cond DO body",
      "{ body } REPEAT and REPEATWHILE/REPEATUNTIL",
    ],
    prereqs: ["07-for-loop"],
  },
  {
    slug: "09-switchon",
    title: "SWITCHON",
    level: 2,
    topic: "control",
    summary: "Multi-way dispatch with CASE, DEFAULT, ENDCASE.",
    goals: [
      "SWITCHON expr INTO { CASE k: … ENDCASE }",
      "DEFAULT branch",
      "How ENDCASE differs from implicit fallthrough in C",
    ],
    prereqs: ["07-for-loop"],
  },

  // ---- Level 3 — Functions & Scope ------------------------------
  {
    slug: "10-functions",
    title: "Functions & Routines",
    level: 3,
    topic: "functions",
    summary: "Value-returning functions (=) vs side-effect routines (BE).",
    goals: [
      "LET sqr(x) = x*x — returns a value",
      "LET greet(s) BE writef(\"hi %s*n\", s) — returns nothing",
      "Pass primitives; everything's a word",
      "RETURN vs RESULTIS",
    ],
    prereqs: ["05-conditionals"],
  },
  {
    slug: "11-recursion",
    title: "Recursion",
    level: 3,
    topic: "functions",
    summary: "Self-calling functions. Factorial walk-through.",
    goals: [
      "Base case + recursive case",
      "The call stack",
      "When recursion beats iteration (and when it doesn't)",
    ],
    prereqs: ["10-functions"],
  },
  {
    slug: "12-valof",
    title: "VALOF / RESULTIS",
    level: 3,
    topic: "functions",
    summary: "Turn a block into an expression that yields a value.",
    goals: [
      "VALOF { … RESULTIS v }",
      "Local variables inside a VALOF block",
      "Nested VALOF",
    ],
    prereqs: ["10-functions"],
  },
  {
    slug: "13-nested-fns",
    title: "Nested Functions",
    level: 3,
    topic: "functions",
    summary: "Functions declared inside VALOF. The compiler hoists them.",
    goals: [
      "Scope rules for nested LET inside VALOF",
      "Access outer-function variables",
      "Helpers that only make sense inside one caller",
    ],
    prereqs: ["12-valof"],
  },
  {
    slug: "14-cgoto",
    title: "Computed GOTO",
    level: 3,
    topic: "functions",
    summary: "Take the address of a local label and jump to it at runtime.",
    goals: [
      "Declare labels with `name:`",
      "Capture label addresses",
      "Use an index into a table of labels for dispatch",
    ],
    prereqs: ["09-switchon"],
  },

  // ---- Level 4 — Data Structures --------------------------------
  {
    slug: "15-vectors",
    title: "Vectors",
    level: 4,
    topic: "data",
    summary: "VEC n and the ! word-indexing operator.",
    goals: [
      "LET v = VEC 10 gives a stack vector",
      "v!0, v!1, … are word slots",
      "Initialise with FOR",
      "Pass vectors to functions",
    ],
    prereqs: ["07-for-loop"],
  },
  {
    slug: "16-multidim",
    title: "Multi-dimensional Data",
    level: 4,
    topic: "data",
    summary: "Dynamic heap vectors (getvec/freevec) and vector-of-vectors.",
    goals: [
      "getvec(n) for heap allocation",
      "freevec(v) to return memory",
      "Vector of vectors for 2-D tables",
      "When to choose heap vs VEC",
    ],
    prereqs: ["15-vectors"],
  },
  {
    slug: "17-bit-manipulation",
    title: "Bit Manipulation",
    level: 4,
    topic: "data",
    summary: "Shifts, logical ops, and setbit/testbit for bit vectors.",
    goals: [
      "LSHIFT / RSHIFT (logical)",
      "LOGAND / LOGOR / XOR / EQV bitwise ops",
      "setbit / testbit on a word bit-vector",
      "Packing flags into a single word",
    ],
    prereqs: ["03-variables"],
  },
  {
    slug: "18-bitfield",
    title: "Bit Fields (SLCT / OF)",
    level: 4,
    topic: "data",
    summary: "SLCT length:shift:offset and the OF operator.",
    goals: [
      "MANIFEST a field selector with SLCT",
      "Read fields: (SLCT l:s:o) OF ptr",
      "Write fields: (SLCT l:s:o) OF ptr := value",
      "When SLCT is worth the trouble",
    ],
    prereqs: ["17-bit-manipulation"],
  },
  {
    slug: "19-manifest-static",
    title: "MANIFEST and STATIC",
    level: 4,
    topic: "data",
    summary: "Compile-time constants vs program-global state.",
    goals: [
      "MANIFEST { name = value } for constants",
      "STATIC { name = value } for persistent storage",
      "When each applies",
    ],
    prereqs: ["03-variables"],
  },
  {
    slug: "34-binary-tree",
    title: "Binary Search Tree",
    level: 4,
    topic: "data",
    summary: "Heap-allocated BST: getvec nodes, recursive insert/lookup/inorder, freevec cleanup.",
    goals: [
      "getvec(n) returns a 0..n vector; 0 is the null pointer",
      "MANIFEST gives readable field offsets on plain vectors",
      "Recursive insert returning the (possibly new) root",
      "Iterative lookup with a sentinel for misses",
      "Post-order freevec releases the whole tree",
    ],
    prereqs: ["15-vectors", "19-manifest-static"],
  },

  // ---- Level 5 — I/O & System ----------------------------------
  {
    slug: "20-stdin-echo",
    title: "Reading stdin",
    level: 5,
    topic: "io",
    summary: "rdch() in a loop until EOF.",
    goals: [
      "rdch returns next char or -1 at EOF",
      "Echo input back with wrch",
      "Loop termination on EOF",
    ],
    prereqs: ["08-while-until"],
  },
  {
    slug: "21-streams",
    title: "Named Streams",
    level: 5,
    topic: "io",
    summary: "Open, select, and close write + read streams.",
    goals: [
      "findoutput(name) opens a write stream",
      "selectoutput(h) switches current output",
      "endstream commits data to storage",
      "Round-trip via findinput",
    ],
    prereqs: ["20-stdin-echo"],
  },
  {
    slug: "22-format-output",
    title: "Formatted Output",
    level: 5,
    topic: "io",
    summary: "writed, writeu, writez, writehex, writeoct, writeflt, writee.",
    goals: [
      "Signed vs unsigned widths",
      "Zero vs space padding",
      "Hex/oct widths",
      "Float fixed-point and exponential",
    ],
    prereqs: ["03-variables"],
  },
  {
    slug: "23-parsing",
    title: "Reading Numbers & Tokens",
    level: 5,
    topic: "io",
    summary: "readn, rditem, str2numb, string_to_number.",
    goals: [
      "readn parses integers from input",
      "rditem returns token type codes",
      "string_to_number: full parser, value in result2",
      "Check result2 for success",
    ],
    prereqs: ["21-streams"],
  },
  {
    slug: "24-rdargs",
    title: "Command-line Args",
    level: 5,
    topic: "io",
    summary: "rdargs parses argv against a key-spec string.",
    goals: [
      "Write a FROM/A,TO/K,N/K/N,-v/S spec",
      "Inspect argv after rdargs",
      "/A required, /K keyed, /N numeric, /S switch",
    ],
    prereqs: ["04-strings-chars"],
  },
  {
    slug: "25-floats",
    title: "Floating Point (FLT mode)",
    level: 5,
    topic: "io",
    summary: "FLT feature: # prefix for float ops, #:= assignment.",
    goals: [
      "Write float constants: 3.14, 1.0e-3",
      "Float ops: #+ #- #* #/ #MOD",
      "Float compare: #= #~= #< #> #<= #>=",
      "Convert via FLT/FIX",
    ],
    prereqs: ["03-variables"],
  },

  // ---- Level 6 — Advanced / Bonus -------------------------------
  {
    slug: "26-match-patterns",
    title: "MATCH Expressions",
    level: 6,
    topic: "advanced",
    summary: "MCPL pattern matching: ranges, alternatives, guards.",
    goals: [
      "MATCH (args) : pat ,.., pat => expr",
      "Ranges like 0..9, alternatives a|b|c",
      "NEXT and EXIT inside a MATCH",
      "MATCH command form (side effects)",
    ],
    prereqs: ["09-switchon"],
  },
  {
    slug: "27-every-sum",
    title: "EVERY Expressions",
    level: 6,
    topic: "advanced",
    summary: "Run every matching arm and accumulate the results.",
    goals: [
      "EVERY (args) : pat ,.., pat => expr",
      "All matching arms contribute",
      "Result type inferred from arm expressions",
    ],
    prereqs: ["26-match-patterns"],
  },

  // ---- Level 7 — Objects ----------------------------------------
  {
    slug: "28-method-sugar",
    title: "Method-call Sugar",
    level: 7,
    topic: "objects",
    summary: "E#(args) desugars to (args0!0!E)(args) at compile time.",
    goals: [
      "Understand BCPL's OOP calling convention",
      "Build a methods vector and point obj!0 at it",
      "Use E#(obj, …) and its equivalent (obj!0!E)(obj, …)",
    ],
    prereqs: ["15-vectors"],
  },
  {
    slug: "29-first-class",
    title: "Your First Class",
    level: 7,
    topic: "objects",
    summary: "Class = methods vector + fields vector. init/destroy convention.",
    goals: [
      "Layout methods and fields vectors",
      "InitObj (slot 0) and CloseObj (slot 1) convention",
      "Write a tiny local mkobj that allocates + initialises",
      "Create multiple instances sharing one methods vector",
    ],
    prereqs: ["28-method-sugar"],
  },
  {
    slug: "30-inheritance",
    title: "Inheritance",
    level: 7,
    topic: "objects",
    summary: "Derive a class; override methods; call super via back-pointer.",
    goals: [
      "Copy parent methods into the derived methods vector",
      "Override selected methods",
      "Keep a private slot holding the parent's method to call super",
    ],
    prereqs: ["29-first-class"],
  },
  {
    slug: "31-mkobj-helper",
    title: "A Reusable mkobj",
    level: 7,
    topic: "objects",
    summary: "Generic mkobj: one helper, any class following the InitObj convention.",
    goals: [
      "Encapsulate the allocate-and-initialise pattern",
      "Pass init arguments via @a (address-of-first-arg)",
      "Apply the same helper to different classes",
    ],
    prereqs: ["29-first-class"],
  },

  // ---- Level 8 — Coroutines -------------------------------------
  {
    slug: "32-coroutines",
    title: "Coroutines",
    level: 8,
    topic: "coroutines",
    summary: "createco, callco, cowait — cooperative multitasking BCPL-style.",
    goals: [
      "Allocate a coroutine with its own stack via createco(fn, size)",
      "callco(c, arg) suspends the caller, resumes c with arg",
      "cowait(arg) yields control back to the parent",
      "Body fn gets the first callco arg as its parameter",
    ],
    prereqs: ["10-functions"],
  },

  // ---- Level 9 — Graphics --------------------------------------
  {
    slug: "33-sdl-bouncer",
    title: "SDL: Bouncing Ball",
    level: 9,
    topic: "graphics",
    summary: "Canvas-backed SDL ops: setvideomode, maprgb, drawfillcircle, fillsurf.",
    goals: [
      "GET \"sdl\" + sys(Sys_sdl, sdl_init) reveals the canvas pane",
      "sdl_setvideomode picks the canvas size",
      "sdl_maprgb packs (r,g,b) into a colour int",
      "Drawing ops take (surf, ...args, colour)",
      "sdl_flip is a no-op (canvas auto-presents)",
    ],
    prereqs: ["07-for-loop"],
  },
  {
    slug: "35-raycaster",
    title: "SDL: Wolfenstein-style Raycaster",
    level: 9,
    topic: "graphics",
    summary: "Flat-shaded raycast walls over an 8x8 grid; per-column vertical strips.",
    goals: [
      "Fixed-point map coordinates (1024 units per cell)",
      "BCPL Taylor sin/cos baked into fixed-point lookup tables",
      "Per-column ray cast by marching small steps until a wall cell",
      "Wall slice height = projection_const / distance",
      "Distance shading via sdl_maprgb at draw time",
    ],
    prereqs: ["33-sdl-bouncer", "25-floats", "34-binary-tree"],
  },
  {
    slug: "36-raycaster-tex",
    title: "SDL: Raycaster with Texture Pipeline",
    level: 9,
    topic: "graphics",
    summary: "Higher-res raycaster wired for texture mapping: side detection, wallX, per-band column draw.",
    goals: [
      "STRIDE = 1 — one ray per pixel column",
      "cast() reports (perpendicular distance, side, wallX)",
      "Wall column rendered as N texY bands instead of one rect",
      "Procedural brick texture stands in for a real texel array",
      "Fisheye correction via cos(angle delta from heading)",
    ],
    prereqs: ["35-raycaster"],
  },
  {
    slug: "37-raycaster-textured",
    title: "SDL: Real Texture Mapping",
    level: 9,
    topic: "graphics",
    summary: "Loads an uploaded PNG via the Assets tab and samples real texels per band.",
    goals: [
      "Sys_assetload maps a decoded PNG into wasm memory",
      "Direct texel lookup: tbase!(texY * tw + texX)",
      "ANG = 8192, FOV = 1365 — finer angular resolution to kill silhouette stair-step",
      "NS-face dimming via per-channel halving",
    ],
    prereqs: ["36-raycaster-tex"],
  },
  {
    slug: "38-raycaster-skyfloor",
    title: "SDL: Sky Panorama + Floor & Ceiling Cast",
    level: 9,
    topic: "graphics",
    summary: "Textured sky (sampled by ray angle), textured floor and ceiling (per-pixel floorcast) on top of textured walls.",
    goals: [
      "Sys_setbgtex caches sky/floor/ceiling textures once",
      "Sys_drawskycol samples a panorama by ray angle for U",
      "Sys_drawfloorcol per-pixel cast: rowDist = horizon / (y - horizon)",
      "Three uploaded PNGs combine for full environment texturing",
    ],
    prereqs: ["37-raycaster-textured"],
  },
  {
    slug: "39-wad-reader",
    title: "Doom WAD Reader",
    level: 9,
    topic: "graphics",
    summary: "Parse a Doom WAD file header and lump directory in pure BCPL using a binary asset upload.",
    goals: [
      "Sys_assetload now accepts arbitrary binary blobs (info!1 = 0)",
      "BCPL byte-fetch operator `base % i` reads raw bytes from wasm memory",
      "Little-endian i32 decode from bytes",
      "Walk the WAD lump directory; print filepos, size, 8-byte name",
    ],
    prereqs: ["37-raycaster-textured"],
  },
  {
    slug: "40-doom-mapview",
    title: "Doom 2D Map View",
    level: 9,
    topic: "graphics",
    summary: "First step toward a Doom BSP renderer: auto-detect ExMy/MAPxx, decode VERTEXES + LINEDEFS, draw the map as a top-down automap.",
    goals: [
      "Auto-detect a map marker lump (ExMy or MAPxx) in the WAD dir",
      "Read int16 vertex coords; sign-extend negative values",
      "Compute bbox + scale to fit canvas (aspect-preserving)",
      "Draw each linedef as one Sys_sdl sdl_drawline call",
      "Two-sided linedefs (back ~= #xFFFF) drawn dimmer for portal hint",
    ],
    prereqs: ["39-wad-reader"],
  },
  {
    slug: "41-doom-mapnav",
    title: "Doom Map + Player Nav",
    level: 9,
    topic: "graphics",
    summary: "Lay the camera transform code: parse THINGS, spawn at player1 start, WASD/arrows pan and turn the player marker over the 2D map.",
    goals: [
      "Parse THINGS lump (10 bytes/entry); pick type=1 (player1 start)",
      "Convert Doom degrees to our 8192-tick angle space",
      "Sin/cos LUT (same shape as raycasters 35–38)",
      "Player marker + facing line drawn through the same projection",
      "Free-fly nav (no wall collision yet) — sets up state the 3D renderer will need",
    ],
    prereqs: ["40-doom-mapview"],
  },
  {
    slug: "42-doom-3dview",
    title: "Doom 3D Walls (no BSP, no textures)",
    level: 9,
    topic: "graphics",
    summary: "First-person Doom wall renderer. Per-column projection, near-plane clip, backface cull. Flat-shaded by sector light. No BSP yet — overdraw is visible in cluttered scenes.",
    goals: [
      "Parse SIDEDEFS (30 bytes) and SECTORS (26 bytes) for floor/ceil/light",
      "Camera transform: camY = rx·cos+ry·sin (depth), camX = rx·sin-ry·cos (lateral)",
      "Backface cull for 1-sided linedefs via cross product",
      "Near-plane clip by interpolating to NEAR before dividing by z",
      "Per-column perspective-correct interp of 1/z, project floor/ceil",
      "Two-sided portals draw lower/upper steps where sector heights differ",
    ],
    prereqs: ["41-doom-mapnav"],
  },
  {
    slug: "43-doom-bsp",
    title: "Doom BSP Traversal + Clip Windows",
    level: 9,
    topic: "graphics",
    summary: "Replaces 42's brute-force linedef loop with a real Doom-style BSP walk. Per-column clip windows fix overdraw; point_in_subsector gives a real camera floor height.",
    goals: [
      "Parse NODES (28 B), SSECTORS (4 B), SEGS (12 B)",
      "render_node() walks BSP front-to-back via R_PointOnSide test",
      "Per-column col_top[] / col_bot[] track open vertical band",
      "Portal step closes the column from top/bottom; solid wall closes it entirely",
      "Early-out when cols_open reaches 0 — far subsectors skipped",
      "point_in_subsector(x, y) → real sector → cam_z = floor + 41",
      "Leftover open columns filled with sky / floor backdrop",
    ],
    prereqs: ["42-doom-3dview"],
  },
  {
    slug: "44-doom-wall-tex",
    title: "Doom Wall Textures",
    level: 9,
    topic: "graphics",
    summary: "Decode PLAYPAL + PNAMES + TEXTURE1, composite patches into RGBA buffers, render walls with perspective-correct U via the new Sys_drawwallcol op (tiles V instead of stretching).",
    goals: [
      "PLAYPAL → 256 packed RGBA words",
      "TEXTURE1 + PNAMES → composite patches into per-texture RGBA buffer",
      "Texture cache keyed by 8-byte name; pre-built from all sidedefs",
      "Sys_drawwallcol = 86: per-pixel V wrapped mod tex_h (Doom-style tiling)",
      "Perspective-correct U via linear interp of u/z + 1/z, divide per column",
      "Integer sqrt for world wall length",
    ],
    prereqs: ["43-doom-bsp"],
  },
  {
    slug: "45-doom-flats",
    title: "Doom Floor + Ceiling Flats",
    level: 9,
    topic: "graphics",
    summary: "Decode 64×64 flats from PLAYPAL and render textured floor / ceiling via Sys_drawflatspan (per-pixel reverse projection).",
    goals: [
      "SECTOR.floor_tex / ceil_tex (8-byte names) → flat cache",
      "Each flat is 4096 bytes of palette indices → 64×64 RGBA buffer",
      "Sys_drawflatspan = 87: per-pixel rowDist = abs(cam_above) * F_X / |y-HORIZON|",
      "Per-column ray dx/dy = fwd + right * (col - W/2) / F_X",
      "F_SKY1 detected and skipped — falls back to sky_col",
    ],
    prereqs: ["44-doom-wall-tex"],
  },
  {
    slug: "46-doom-light",
    title: "Doom Distance Light Diminishing",
    level: 9,
    topic: "graphics",
    summary: "Per-column sector-light + distance fade. Sys_setlight caches a scale; drawwallcol/drawflatspan multiply per-pixel RGB. Iconic Doom dark-edge look.",
    goals: [
      "Sys_setlight = 88: caches light scale (0..256) for next draw calls",
      "Per-column: light = sector_light − cy/LIGHT_DROP, floored at LIGHT_FADE_MIN",
      "Drawwallcol / drawflatspan apply ((c * scale) >> 8) per channel",
      "Fast-path identity loop when scale = 256 (full bright) preserved",
    ],
    prereqs: ["45-doom-flats"],
  },
  {
    slug: "47-doom-pegging",
    title: "Doom Texture Pegging + Portal Mid-Textures",
    level: 9,
    topic: "graphics",
    summary: "Honor ML_DONTPEGTOP / ML_DONTPEGBOTTOM flags. Render portal mid-textures (railings, fences) with alpha-test transparency via negated v_step.",
    goals: [
      "LINEDEF.flags decoded; per-part y_anchor computed from pegging",
      "Solid wall: default anchor = front_ceil; ML_DONTPEGBOTTOM = floor + tex_h",
      "Upper step: default anchor = back_ceil + tex_h; ML_DONTPEGTOP = front_ceil",
      "Lower step: default = front_ceil; ML_DONTPEGBOTTOM = back_floor + tex_h",
      "Portal mid-tex: drawn with transparency (drawwallcol skips word==0 when v_step < 0)",
      "Limitation: mid-tex drawn inline front-to-back, can be overdrawn by farther segs",
    ],
    prereqs: ["46-doom-light"],
  },
  {
    slug: "48-doom-sprites",
    title: "Doom Sprites",
    level: 9,
    topic: "graphics",
    summary: "Per-column z-buffer + sprite cache + Doom THING type → sprite name map. Renders barrels, ammo, armor, monsters, etc. with wall occlusion via col_z.",
    goals: [
      "col_z[W] tracks nearest wall cy per column during BSP traversal",
      "Sprite cache: load patch by name, store w/h/leftofs/topofs + RGBA buffer",
      "Hardcoded THING type → 4-char sprite + frame letter + rotation digit",
      "draw_sprite: cam transform → screen rect → per-column drawwallcol",
      "Sprite occlusion: skip col if sprite cy >= col_z[col_x]",
      "Transparency via negated v_step_q16",
    ],
    prereqs: ["47-doom-pegging"],
  },
  {
    slug: "49-doom-collide",
    title: "Doom Wall + Floor Collision",
    level: 9,
    topic: "graphics",
    summary: "try_move() with axis-aligned slide. Blocks moves that climb stairs taller than STEP_MAX or push the player into a ceiling.",
    goals: [
      "sector_at(x, y) → floor_at / ceil_at convenience accessors",
      "can_move(): new_floor − cur_floor ≤ STEP_MAX (24); new_ceil − new_floor ≥ PLAYER_H (56)",
      "try_move(): full diagonal first; on block try X-only then Y-only",
      "1-sided walls block naturally — opposite side is a huge floor step",
    ],
    prereqs: ["48-doom-sprites"],
  },
  {
    slug: "50-doom-sky",
    title: "Doom Sky Cylinder",
    level: 9,
    topic: "graphics",
    summary: "Render SKY1 as a 360° panorama. Sectors with F_SKY1 ceilings + leftover void columns sample the sky by player angle.",
    goals: [
      "Composite SKY1 from TEXTURE1 via existing wall-tex pipeline",
      "Register via Sys_setbgtex slot 0",
      "Sys_drawskyspan = 89: V mapped to absolute screen y (sky doesn't tilt)",
      "U = (pa * sky_w / (ANG/4) + col_x * sky_w / W) REM sky_w",
      "Ceiling band uses sky when sector_ceil_is_sky(front_sec)",
    ],
    prereqs: ["49-doom-collide"],
  },
  {
    slug: "51-doom-rot",
    title: "Doom Sprite Sort + Monster Rotations",
    level: 9,
    topic: "graphics",
    summary: "Painter's back-to-front sort fixes sprite overlap flicker. 8 rotation frames per monster picked by viewer bearing in monster's local frame.",
    goals: [
      "viewer_octant: rotate (px-tx, py-ty) into monster's local frame; pick 0..7",
      "build_monster_name: base + 'A' + ('1' + octant) → sprite lump",
      "draw_sprites: collect visible into vs_* arrays; insertion-sort by cay desc; draw",
      "Pickups still use frame ?A0 (no rotation)",
    ],
    prereqs: ["50-doom-sky"],
  },
  {
    slug: "52-doom-doors",
    title: "Doom Door / Use Action",
    level: 9,
    topic: "graphics",
    summary: "Press E/Space to open doors. Sector ceiling animates upward to (lowest_neighbor_ceil − 4) at DOOR_SPEED units/frame.",
    goals: [
      "ceil_h_runtime[] overrides static WAD ceiling; sec_ceil() reads runtime",
      "pick_use_line: nearest linedef in front of player within USE_RANGE",
      "is_use_door_special: specials 1 / 31 / 117 / 118 trigger open",
      "lowest_neighbor_ceil(s): scan all linedefs touching s, find min other-side ceil",
      "tick_doors() each frame raises opening sectors by DOOR_SPEED",
      "Edge-detect on use_prev so a held key opens once",
    ],
    prereqs: ["51-doom-rot"],
  },
];

// Quick-lookup helpers used by the UI.
export const BY_SLUG = new Map(TRACK.map(e => [e.slug, e]));

export function nextSlug(slug) {
  const i = TRACK.findIndex(e => e.slug === slug);
  return i >= 0 && i < TRACK.length - 1 ? TRACK[i + 1].slug : null;
}
export function prevSlug(slug) {
  const i = TRACK.findIndex(e => e.slug === slug);
  return i > 0 ? TRACK[i - 1].slug : null;
}
